// Server-rendered agency content migrated from the validated standalone site.
export const agencyMarkup = `
<a class="skip" href="#main">Skip to content</a>
<header class="header"><div class="wrap header-inner">
<a class="brand" href="#" aria-label="Oneclick Digital Solution home"><img src="/agency/assets/oneclick-logo.png" width="2048" height="546" alt="Oneclick Digital Solution"></a>
<button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button>
<nav id="navigation" aria-label="Main navigation"><a href="#packages">Packages</a><a href="#services">Services</a><a href="#faq">FAQ</a><a class="button button-small" data-contact href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Let’s Talk <span aria-hidden="true">↗</span></a></nav>
</div></header>
<main id="main">
<section class="hero wrap" aria-labelledby="hero-title">
<div class="hero-copy"><p class="eyebrow"><span class="blue-dot"></span> YOUR NEXT CHAPTER STARTS HERE</p>
<h1 id="hero-title">A better website.<br>A stronger<br><span>first impression.</span></h1>
<p class="intro">Professional websites and digital services that help your business look credible and make it easy for customers to contact you.</p>
<div class="hero-actions"><a class="button" href="#packages">View Packages <span aria-hidden="true">↗</span></a><a class="text-link" data-contact href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Chat on WhatsApp <span aria-hidden="true">↗</span></a></div>
<p class="hero-note" id="hero-offer">Websites built around your business.</p></div>
<div class="hero-art" aria-label="Illustrative website design concept"><div class="art-grid"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div>
<div class="concept"><div class="browser-bar"><div class="dots"><i></i><i></i><i></i></div><span>Design concept</span><span aria-hidden="true">↗</span></div>
<div class="concept-content"><div class="concept-nav"><strong>FORM<span> / </span>SPACE</strong><span>INTERIOR DESIGN</span></div><div class="concept-body"><div class="concept-copy"><span class="concept-eyebrow">THOUGHTFULLY DESIGNED.</span><h2>Spaces made<br>for living.</h2><p>A little more room<br>for what matters.</p><span class="concept-cta">Explore our work <b>↗</b></span></div><div class="architecture" aria-hidden="true"><div class="sun"></div><div class="arch"></div><div class="step step-one"></div><div class="step step-two"></div><div class="sphere"></div></div></div><div class="concept-bottom"><span>Considered. Crafted. Yours.</span><span>01 / 03</span></div></div>
</div><div class="art-caption"><span class="caption-line"></span> GOOD DESIGN. A CLEAR NEXT STEP.</div>
</div>
</section>
<section class="packages" id="packages" aria-labelledby="packages-title"><div class="wrap">
<div class="section-top"><div><p class="eyebrow">BIG FIRST IMPRESSION. CLEAR PRICING.</p><h2 id="packages-title">Your next move, made simple.</h2><p class="section-sub" id="campaign-sub">Choose the right starting point for your business.</p></div><div class="campaign"><p id="campaign-status" role="status">Website packages</p><div class="countdown" role="timer" aria-label="Time remaining in the website offer" aria-live="off"><div><b id="days">00</b><span>Days</span></div><i>:</i><div><b id="hours">00</b><span>Hours</span></div><i>:</i><div><b id="minutes">00</b><span>Minutes</span></div><i>:</i><div><b id="seconds">00</b><span>Seconds</span></div></div><p id="deadline" class="deadline">Campaign dates: September 16–30, 2026, UAE time.</p></div></div>
<div class="pricing-grid">
<article class="price-card featured"><div class="card-top"><span class="package-index">01 / THE FIRST STEP</span><span class="offer-badge" id="starter-badge">STARTER</span></div><h3>Starter</h3><p class="card-description">A professional public website for your business.</p><div class="price-block" id="starter-price"><p class="current-price">Contact us for current pricing.</p></div><p class="price-caption">One-time project price</p><ul><li>Up to 5 pages</li><li>Mobile-responsive design</li><li>Business and services information</li><li>WhatsApp contact button</li><li>Social media links</li><li>Basic on-page SEO</li></ul><p class="scope">Public website only.<br>No admin dashboard.</p><a class="button card-button" id="starter-link" href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Choose Starter <span aria-hidden="true">↗</span></a></article>
<article class="price-card"><div class="card-top"><span class="package-index">02 / ROOM TO GROW</span></div><h3>Business</h3><p class="card-description">More room to showcase your business and receive inquiries.</p><div class="price-block" id="business-price"></div><p class="price-caption">One-time project price</p><ul><li>Up to 8 pages</li><li>Custom business-focused design</li><li>Mobile-responsive layout</li><li>Contact and inquiry forms</li><li>WhatsApp integration</li><li>Basic on-page SEO</li><li>30 days of post-launch support</li></ul><p class="scope">No admin dashboard.</p><a class="button button-outline card-button" id="business-link" href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Choose Business <span aria-hidden="true">↗</span></a></article>
<article class="price-card"><div class="card-top"><span class="package-index">03 / MORE CONTROL</span></div><h3>Business System</h3><p class="card-description">A public website with basic admin controls.</p><div class="price-block" id="system-price"></div><p class="price-caption">One-time project price</p><ul><li>Public website and admin login</li><li>Manage one agreed content type: products OR services</li><li>Basic inquiry management</li><li>Mobile-responsive design</li><li>Basic on-page SEO</li><li>60 days of post-launch support</li></ul><p class="scope">Final price depends on the agreed scope. Booking, online payments, customer accounts and advanced workflows are quoted separately.</p><a class="button button-outline card-button" id="system-link" href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Discuss Your System <span aria-hidden="true">↗</span></a></article>
</div><p class="pricing-note">Domain, hosting, paid tools and third-party subscriptions are quoted separately unless included in your written proposal.</p>
<noscript><p class="noscript">Please enable JavaScript for package prices and the live offer countdown, or contact us on WhatsApp for current pricing.</p></noscript>
</div></section>
<section class="services wrap" id="services" aria-labelledby="services-title"><div class="services-heading"><div><p class="eyebrow">BEYOND THE WEBSITE</p><h2 id="services-title">More ways to grow<br>your business.</h2></div><p>A consistent presence, wherever<br>your customers find you.<br><span>Other services are quoted individually.</span></p></div><div class="service-grid">
<article><span class="service-icon" aria-hidden="true">↗</span><h3>Website Design<br>and Development</h3><p>A clear, welcoming home for your business online.</p></article><article><span class="service-icon" aria-hidden="true">◈</span><h3>Branding and<br>Graphic Design</h3><p>A visual identity that feels like your business.</p></article><article><span class="service-icon" aria-hidden="true">◎</span><h3>Social Media<br>Management</h3><p>Keep your pages active and your message consistent.</p></article><article><span class="service-icon" aria-hidden="true">↗</span><h3>Digital<br>Marketing</h3><p>Thoughtful campaigns built around your goals.</p></article><article><span class="service-icon" aria-hidden="true">▷</span><h3>Video Editing and<br>Content Creation</h3><p>Turn your ideas into content worth watching.</p></article>
</div><p class="value-line">Direct communication. <span>Business-focused design.</span> Clear scope. <span>Support after launch.</span></p></section>
<section class="faq wrap" id="faq" aria-labelledby="faq-title"><div><p class="eyebrow">A LITTLE CLARITY</p><h2 id="faq-title">Good questions.<br>Straight answers.</h2></div><div class="faq-list">
<details><summary id="starter-question">What is included in the Starter package?</summary><p id="starter-answer">A mobile-responsive public website with up to five pages, business and services information, WhatsApp contact, social links and basic on-page SEO. It does not include an admin dashboard. Contact us for current pricing.</p></details>
<details><summary>Can I update the website myself?</summary><p>The Business System package includes admin controls for the agreed content. Starter and Business packages do not include a self-service dashboard; changes can be requested separately.</p></details>
<details><summary>Are domain and hosting included?</summary><p>Domain, hosting, paid tools and third-party subscriptions are quoted separately unless included in your written proposal.</p></details>
<details><summary>How long does development take?</summary><p>We confirm your delivery timeline after reviewing the scope and receiving the required content, logo and images.</p></details>
</div></section>
<section class="closing wrap" aria-labelledby="closing-title"><div><p class="eyebrow">LET’S MAKE IT HAPPEN</p><h2 id="closing-title">Ready to build your<br>business online?</h2></div><a class="button button-white" data-contact href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer">Let’s Talk on WhatsApp <span aria-hidden="true">↗</span></a></section>
</main>
<footer class="wrap"><div class="footer-top"><a class="brand" href="#" aria-label="Oneclick Digital Solution home"><img src="/agency/assets/oneclick-logo.png" width="2048" height="546" alt="Oneclick Digital Solution"></a><nav aria-label="Footer navigation"><a href="#packages">Packages</a><a href="#services">Services</a><a href="#faq">FAQ</a></nav><a id="phone" href="tel:+971567654647">056 765 4647</a></div><p class="copyright">© 2026 Oneclick Digital Solution. All rights reserved.</p></footer>
<a class="floating-contact" data-contact href="https://wa.me/971567654647" target="_blank" rel="noopener noreferrer" aria-label="Chat with Oneclick Digital Solution on WhatsApp"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 11.6a8 8 0 0 1-11.9 7L4 20l1.4-4.2A8 8 0 1 1 20 11.6Z" stroke="currentColor" stroke-width="1.7"/><path d="M9 7.8c.3-.1 1 1.5 1 1.8s-.7.7-.6 1c.4 1 1.7 2.3 2.7 2.7.3.1.8-.6 1.1-.6s1.8.7 1.8 1c0 .8-.8 1.5-1.6 1.4-3-.4-5.7-3.1-6-5.7-.1-.8.7-1.6 1.6-1.6Z" fill="currentColor"/></svg></a>
`;
